import { Inject, Injectable } from '@nestjs/common';
import { ACCOUNTS_REPOSITORY } from '../ports/accounts.repository.token';
import type { AccountRepository } from '../ports/accounts.repository.interface';
import { Account } from '../../domain/entities/account.entity';

const PCG: { code: string; name: string; class: number }[] = [
  // ─────────────────────────────────────────────────────────────────────
  // CLASSE 1 — Comptes de capitaux
  // ─────────────────────────────────────────────────────────────────────
  { code: '101',    name: 'Capital social ou individuel',                                class: 1 },
  { code: '1011',   name: 'Capital souscrit — non appelé',                               class: 1 },
  { code: '1012',   name: 'Capital souscrit — appelé, non versé',                        class: 1 },
  { code: '1013',   name: 'Capital souscrit — appelé, versé',                            class: 1 },
  { code: '104',    name: 'Primes liées au capital social',                              class: 1 },
  { code: '1041',   name: "Primes d'émission",                                           class: 1 },
  { code: '1042',   name: 'Primes de fusion',                                            class: 1 },
  { code: '1043',   name: "Primes d'apport",                                             class: 1 },
  { code: '1044',   name: "Primes de conversion d'obligations en actions",               class: 1 },
  { code: '105',    name: 'Écarts de réévaluation',                                      class: 1 },
  { code: '1052',   name: 'Réserve spéciale de réévaluation',                            class: 1 },
  { code: '106',    name: 'Réserves',                                                    class: 1 },
  { code: '1061',   name: 'Réserve légale',                                              class: 1 },
  { code: '1062',   name: 'Réserves statutaires ou contractuelles',                      class: 1 },
  { code: '1063',   name: 'Réserves réglementées',                                       class: 1 },
  { code: '1064',   name: 'Réserves facultatives',                                       class: 1 },
  { code: '108',    name: "Compte de l'exploitant",                                      class: 1 },
  { code: '109',    name: 'Actionnaires — Capital souscrit non appelé',                  class: 1 },
  { code: '110',    name: 'Report à nouveau (solde créditeur)',                           class: 1 },
  { code: '119',    name: 'Report à nouveau (solde débiteur)',                            class: 1 },
  { code: '120',    name: "Résultat de l'exercice (bénéfice)",                           class: 1 },
  { code: '129',    name: "Résultat de l'exercice (perte)",                              class: 1 },
  { code: '131',    name: "Subventions d'équipement",                                    class: 1 },
  { code: '138',    name: 'Autres subventions d\'investissement',                        class: 1 },
  { code: '139',    name: 'Subventions d\'investissement inscrites au compte de résultat', class: 1 },
  { code: '142',    name: 'Provisions réglementées relatives aux immobilisations',       class: 1 },
  { code: '143',    name: 'Provisions réglementées relatives aux stocks',                class: 1 },
  { code: '145',    name: 'Amortissements dérogatoires',                                 class: 1 },
  { code: '146',    name: 'Provisions spéciales de réévaluation',                        class: 1 },
  { code: '148',    name: 'Autres provisions réglementées',                              class: 1 },
  { code: '151',    name: 'Provisions pour risques',                                     class: 1 },
  { code: '1511',   name: 'Provisions pour litiges',                                     class: 1 },
  { code: '1512',   name: 'Provisions pour garanties données aux clients',               class: 1 },
  { code: '1514',   name: 'Provisions pour amendes et pénalités',                        class: 1 },
  { code: '1515',   name: 'Provisions pour pertes de change',                            class: 1 },
  { code: '1518',   name: 'Autres provisions pour risques',                              class: 1 },
  { code: '153',    name: 'Provisions pour pensions et obligations similaires',          class: 1 },
  { code: '154',    name: 'Provisions pour restructurations',                            class: 1 },
  { code: '155',    name: 'Provisions pour impôts',                                      class: 1 },
  { code: '156',    name: 'Provisions pour renouvellement des immobilisations',          class: 1 },
  { code: '157',    name: 'Provisions pour charges à répartir',                          class: 1 },
  { code: '158',    name: 'Autres provisions pour charges',                              class: 1 },
  { code: '161',    name: 'Emprunts obligataires convertibles',                          class: 1 },
  { code: '162',    name: 'Autres emprunts obligataires',                                class: 1 },
  { code: '163',    name: 'Emprunts auprès des établissements de crédit',                class: 1 },
  { code: '1631',   name: 'Emprunts auprès des établissements de crédit',                class: 1 },
  { code: '1638',   name: 'Intérêts courus sur emprunts bancaires',                      class: 1 },
  { code: '164',    name: 'Emprunts auprès des associés',                                class: 1 },
  { code: '165',    name: 'Dépôts et cautionnements reçus',                              class: 1 },
  { code: '1651',   name: 'Dépôts reçus',                                                class: 1 },
  { code: '1655',   name: 'Cautionnements reçus',                                        class: 1 },
  { code: '166',    name: 'Participation des salariés aux résultats',                    class: 1 },
  { code: '167',    name: 'Emprunts et dettes assimilées',                               class: 1 },
  { code: '168',    name: 'Autres emprunts et dettes assimilées',                        class: 1 },
  { code: '1681',   name: 'Autres emprunts',                                             class: 1 },
  { code: '1686',   name: 'Intérêts courus sur autres dettes',                           class: 1 },
  { code: '169',    name: 'Primes de remboursement des obligations',                     class: 1 },
  { code: '171',    name: 'Dettes rattachées à des participations (groupe)',              class: 1 },
  { code: '174',    name: 'Dettes rattachées à des participations (hors groupe)',         class: 1 },
  { code: '181',    name: 'Comptes de liaison des établissements',                       class: 1 },

  // ─────────────────────────────────────────────────────────────────────
  // CLASSE 2 — Comptes d'immobilisations
  // ─────────────────────────────────────────────────────────────────────
  { code: '201',    name: "Frais d'établissement",                                       class: 2 },
  { code: '2011',   name: 'Frais de constitution',                                       class: 2 },
  { code: '2012',   name: 'Frais de premier établissement',                              class: 2 },
  { code: '2013',   name: "Frais d'augmentation de capital",                             class: 2 },
  { code: '203',    name: 'Frais de recherche et de développement',                      class: 2 },
  { code: '205',    name: 'Concessions, brevets, licences, marques',                     class: 2 },
  { code: '2051',   name: 'Concessions et droits similaires',                            class: 2 },
  { code: '2052',   name: 'Brevets',                                                     class: 2 },
  { code: '2053',   name: 'Licences',                                                    class: 2 },
  { code: '2056',   name: 'Marques',                                                     class: 2 },
  { code: '206',    name: 'Droit au bail',                                               class: 2 },
  { code: '207',    name: 'Fonds commercial',                                            class: 2 },
  { code: '208',    name: 'Autres immobilisations incorporelles',                        class: 2 },
  { code: '211',    name: 'Terrains',                                                    class: 2 },
  { code: '2111',   name: 'Terrains nus',                                                class: 2 },
  { code: '2112',   name: 'Terrains aménagés',                                           class: 2 },
  { code: '2113',   name: 'Sous-sols et sur-sols',                                       class: 2 },
  { code: '2115',   name: 'Terrains bâtis',                                              class: 2 },
  { code: '212',    name: 'Agencements et aménagements de terrains',                     class: 2 },
  { code: '213',    name: 'Constructions',                                               class: 2 },
  { code: '2131',   name: 'Bâtiments',                                                   class: 2 },
  { code: '2135',   name: 'Installations générales des constructions',                   class: 2 },
  { code: '2138',   name: "Ouvrages d'infrastructure",                                   class: 2 },
  { code: '214',    name: "Constructions sur sol d'autrui",                              class: 2 },
  { code: '215',    name: 'Installations techniques, matériel et outillage industriels', class: 2 },
  { code: '2151',   name: 'Installations complexes spécialisées',                        class: 2 },
  { code: '2154',   name: 'Matériel industriel',                                         class: 2 },
  { code: '2155',   name: 'Outillage industriel',                                        class: 2 },
  { code: '2157',   name: 'Agencements du matériel et outillage industriels',            class: 2 },
  { code: '218',    name: 'Autres immobilisations corporelles',                          class: 2 },
  { code: '2181',   name: 'Installations générales et agencements divers',               class: 2 },
  { code: '2182',   name: 'Matériel de transport',                                       class: 2 },
  { code: '2183',   name: 'Matériel de bureau et matériel informatique',                 class: 2 },
  { code: '2184',   name: 'Mobilier',                                                    class: 2 },
  { code: '2185',   name: 'Cheptel',                                                     class: 2 },
  { code: '2186',   name: 'Emballages récupérables',                                     class: 2 },
  { code: '231',    name: 'Immobilisations corporelles en cours',                        class: 2 },
  { code: '232',    name: 'Immobilisations incorporelles en cours',                      class: 2 },
  { code: '237',    name: "Avances sur commandes d'immobilisations incorporelles",       class: 2 },
  { code: '238',    name: "Avances sur commandes d'immobilisations corporelles",         class: 2 },
  { code: '261',    name: 'Titres de participation',                                     class: 2 },
  { code: '266',    name: 'Autres formes de participation',                              class: 2 },
  { code: '267',    name: 'Créances rattachées à des participations',                    class: 2 },
  { code: '271',    name: 'Titres immobilisés autres',                                   class: 2 },
  { code: '272',    name: "Titres immobilisés de l'activité de portefeuille",            class: 2 },
  { code: '273',    name: 'Titres immobilisés (droit de créance)',                       class: 2 },
  { code: '274',    name: 'Prêts',                                                       class: 2 },
  { code: '275',    name: 'Dépôts et cautionnements versés',                             class: 2 },
  { code: '276',    name: 'Autres créances immobilisées',                                class: 2 },
  { code: '277',    name: 'Actions propres ou parts propres',                            class: 2 },
  { code: '2801',   name: "Amortissements — frais d'établissement",                      class: 2 },
  { code: '2803',   name: 'Amortissements — frais de recherche et développement',        class: 2 },
  { code: '2805',   name: 'Amortissements — concessions, brevets, licences',             class: 2 },
  { code: '2807',   name: 'Amortissements — fonds commercial',                           class: 2 },
  { code: '2808',   name: 'Amortissements — autres immobilisations incorporelles',       class: 2 },
  { code: '2811',   name: 'Amortissements — terrains',                                   class: 2 },
  { code: '2812',   name: 'Amortissements — agencements de terrains',                    class: 2 },
  { code: '2813',   name: 'Amortissements — constructions',                              class: 2 },
  { code: '2814',   name: "Amortissements — constructions sur sol d'autrui",             class: 2 },
  { code: '2815',   name: 'Amortissements — installations techniques',                   class: 2 },
  { code: '2818',   name: 'Amortissements — autres immobilisations corporelles',         class: 2 },
  { code: '2905',   name: 'Dépréciations — concessions, brevets',                        class: 2 },
  { code: '2906',   name: 'Dépréciations — droit au bail',                               class: 2 },
  { code: '2907',   name: 'Dépréciations — fonds commercial',                            class: 2 },
  { code: '2908',   name: 'Dépréciations — autres immobilisations incorporelles',        class: 2 },
  { code: '291',    name: 'Dépréciations des immobilisations corporelles',               class: 2 },
  { code: '293',    name: 'Dépréciations des immobilisations en cours',                  class: 2 },
  { code: '296',    name: 'Dépréciations des participations',                            class: 2 },
  { code: '297',    name: 'Dépréciations des autres immobilisations financières',        class: 2 },

  // ─────────────────────────────────────────────────────────────────────
  // CLASSE 3 — Comptes de stocks et en-cours
  // ─────────────────────────────────────────────────────────────────────
  { code: '31',     name: 'Matières premières et fournitures',                           class: 3 },
  { code: '311',    name: 'Matières premières',                                          class: 3 },
  { code: '312',    name: 'Matières consommables',                                       class: 3 },
  { code: '313',    name: 'Matières de conditionnement',                                 class: 3 },
  { code: '32',     name: 'Autres approvisionnements',                                   class: 3 },
  { code: '321',    name: "En-cours d'approvisionnements",                               class: 3 },
  { code: '33',     name: 'En-cours de production de biens',                             class: 3 },
  { code: '331',    name: 'Produits en cours',                                           class: 3 },
  { code: '332',    name: 'Travaux en cours',                                            class: 3 },
  { code: '335',    name: 'Travaux en cours (variation)',                                class: 3 },
  { code: '34',     name: 'En-cours de production de services',                         class: 3 },
  { code: '341',    name: 'Produits intermédiaires',                                     class: 3 },
  { code: '345',    name: 'Produits finis',                                              class: 3 },
  { code: '35',     name: 'Stocks de produits',                                          class: 3 },
  { code: '351',    name: 'Produits intermédiaires',                                     class: 3 },
  { code: '355',    name: 'Produits finis',                                              class: 3 },
  { code: '358',    name: 'Produits résiduels et matières de récupération',              class: 3 },
  { code: '37',     name: 'Stocks de marchandises',                                      class: 3 },
  { code: '370',    name: 'Stocks de marchandises',                                      class: 3 },
  { code: '371',    name: 'Marchandises',                                                class: 3 },
  { code: '391',    name: 'Dépréciations des matières premières',                        class: 3 },
  { code: '392',    name: 'Dépréciations des autres approvisionnements',                 class: 3 },
  { code: '393',    name: 'Dépréciations des en-cours de production de biens',           class: 3 },
  { code: '394',    name: 'Dépréciations des en-cours de production de services',        class: 3 },
  { code: '395',    name: 'Dépréciations des stocks de produits',                        class: 3 },
  { code: '397',    name: 'Dépréciations des stocks de marchandises',                    class: 3 },

  // ─────────────────────────────────────────────────────────────────────
  // CLASSE 4 — Comptes de tiers
  // ─────────────────────────────────────────────────────────────────────
  { code: '401',    name: 'Fournisseurs',                                                class: 4 },
  { code: '4011',   name: 'Fournisseurs — achats de biens et prestations',               class: 4 },
  { code: '4017',   name: 'Fournisseurs — retenues de garantie',                         class: 4 },
  { code: '402',    name: 'Fournisseurs — effets à payer',                               class: 4 },
  { code: '403',    name: 'Fournisseurs — avances et acomptes versés',                   class: 4 },
  { code: '404',    name: "Fournisseurs d'immobilisations",                              class: 4 },
  { code: '405',    name: "Fournisseurs d'immobilisations — effets à payer",             class: 4 },
  { code: '408',    name: 'Fournisseurs — factures non parvenues',                       class: 4 },
  { code: '409',    name: 'Fournisseurs débiteurs',                                      class: 4 },
  { code: '4091',   name: 'Fournisseurs — avances et acomptes versés',                   class: 4 },
  { code: '4096',   name: 'Fournisseurs — créances pour emballages',                     class: 4 },
  { code: '411',    name: 'Clients',                                                     class: 4 },
  { code: '4111',   name: 'Clients — ventes de biens ou prestations',                   class: 4 },
  { code: '4117',   name: 'Clients — retenues de garantie',                              class: 4 },
  { code: '412',    name: 'Clients — effets à recevoir',                                 class: 4 },
  { code: '413',    name: 'Clients — effets escomptés non échus',                        class: 4 },
  { code: '416',    name: 'Clients douteux ou litigieux',                                class: 4 },
  { code: '418',    name: 'Clients — produits non encore facturés',                      class: 4 },
  { code: '419',    name: 'Clients créditeurs',                                          class: 4 },
  { code: '4191',   name: 'Clients — avances et acomptes reçus',                        class: 4 },
  { code: '4196',   name: 'Clients — dettes pour emballages consignés',                 class: 4 },
  { code: '421',    name: 'Personnel — rémunérations dues',                              class: 4 },
  { code: '422',    name: "Comités d'entreprise et œuvres sociales",                     class: 4 },
  { code: '424',    name: 'Participation des salariés aux résultats',                    class: 4 },
  { code: '425',    name: 'Personnel — avances et acomptes',                             class: 4 },
  { code: '426',    name: 'Personnel — dépôts',                                          class: 4 },
  { code: '427',    name: 'Personnel — oppositions',                                     class: 4 },
  { code: '428',    name: 'Personnel — charges à payer et produits à recevoir',          class: 4 },
  { code: '4282',   name: 'Dettes provisionnées pour congés à payer',                    class: 4 },
  { code: '4286',   name: 'Charges à payer — salaires',                                  class: 4 },
  { code: '4287',   name: 'Produits à recevoir — personnel',                             class: 4 },
  { code: '431',    name: 'Sécurité sociale',                                            class: 4 },
  { code: '437',    name: 'Autres organismes sociaux',                                   class: 4 },
  { code: '438',    name: 'Organismes sociaux — charges à payer',                        class: 4 },
  { code: '441',    name: 'État — subventions à recevoir',                               class: 4 },
  { code: '442',    name: 'État — impôts et taxes recouvrables',                         class: 4 },
  { code: '444',    name: 'État — impôts sur les bénéfices',                             class: 4 },
  { code: '4441',   name: 'Acomptes sur impôts sur les bénéfices',                       class: 4 },
  { code: '445',    name: 'État — taxes sur le chiffre d\'affaires',                     class: 4 },
  { code: '4452',   name: 'TVA due intracommunautaire',                                  class: 4 },
  { code: '4455',   name: 'Taxes sur le CA à décaisser',                                 class: 4 },
  { code: '4456',   name: 'Taxes sur le CA déductibles',                                 class: 4 },
  { code: '44562',  name: 'TVA déductible sur immobilisations',                          class: 4 },
  { code: '44566',  name: 'TVA déductible sur autres biens et services',                 class: 4 },
  { code: '44567',  name: 'Crédit de TVA à reporter',                                    class: 4 },
  { code: '44571',  name: 'TVA collectée',                                               class: 4 },
  { code: '44572',  name: 'TVA sur encaissements',                                       class: 4 },
  { code: '4458',   name: 'Taxes sur le CA à régulariser',                               class: 4 },
  { code: '447',    name: 'Autres impôts, taxes et versements assimilés',                class: 4 },
  { code: '448',    name: 'État — charges à payer et produits à recevoir',               class: 4 },
  { code: '451',    name: 'Groupe',                                                      class: 4 },
  { code: '455',    name: 'Associés — comptes courants',                                 class: 4 },
  { code: '456',    name: 'Associés — opérations sur le capital',                        class: 4 },
  { code: '457',    name: 'Associés — dividendes à payer',                               class: 4 },
  { code: '458',    name: 'Associés — opérations faites en commun',                      class: 4 },
  { code: '462',    name: "Créances sur cessions d'immobilisations",                     class: 4 },
  { code: '464',    name: 'Dettes sur acquisitions de valeurs mobilières',               class: 4 },
  { code: '467',    name: 'Autres comptes débiteurs ou créditeurs',                      class: 4 },
  { code: '468',    name: 'Divers — charges à payer et produits à recevoir',             class: 4 },
  { code: '471',    name: "Comptes d'attente",                                           class: 4 },
  { code: '472',    name: 'Comptes transitoires',                                        class: 4 },
  { code: '473',    name: 'Comptes de régularisation divers',                            class: 4 },
  { code: '474',    name: 'Différences sur prix',                                        class: 4 },
  { code: '476',    name: 'Différences de conversion — Actif',                           class: 4 },
  { code: '477',    name: 'Différences de conversion — Passif',                          class: 4 },
  { code: '481',    name: 'Charges à répartir sur plusieurs exercices',                  class: 4 },
  { code: '486',    name: "Charges constatées d'avance",                                 class: 4 },
  { code: '487',    name: 'Produits constatés d\'avance',                                class: 4 },
  { code: '491',    name: 'Dépréciations des comptes de clients',                        class: 4 },
  { code: '495',    name: 'Dépréciations des comptes du groupe et associés',             class: 4 },

  // ─────────────────────────────────────────────────────────────────────
  // CLASSE 5 — Comptes financiers
  // ─────────────────────────────────────────────────────────────────────
  { code: '501',    name: 'Valeurs mobilières de placement',                             class: 5 },
  { code: '5011',   name: 'Actions propres',                                             class: 5 },
  { code: '5013',   name: 'Obligations',                                                 class: 5 },
  { code: '502',    name: 'Actions propres',                                             class: 5 },
  { code: '503',    name: 'Actions',                                                     class: 5 },
  { code: '504',    name: 'Autres valeurs mobilières de placement',                      class: 5 },
  { code: '506',    name: 'Obligations',                                                 class: 5 },
  { code: '507',    name: 'Bons du Trésor et bons de caisse à court terme',              class: 5 },
  { code: '508',    name: 'Autres créances assimilées',                                  class: 5 },
  { code: '511',    name: "Valeurs à l'encaissement",                                    class: 5 },
  { code: '5111',   name: 'Chèques à encaisser',                                         class: 5 },
  { code: '5112',   name: "Chèques remis à l'encaissement",                              class: 5 },
  { code: '512',    name: 'Banques',                                                     class: 5 },
  { code: '5121',   name: 'Banque principale',                                           class: 5 },
  { code: '5124',   name: 'Livret A',                                                    class: 5 },
  { code: '5125',   name: 'Compte à terme',                                              class: 5 },
  { code: '513',    name: 'Chèques postaux',                                             class: 5 },
  { code: '514',    name: 'Chèques postaux',                                             class: 5 },
  { code: '516',    name: 'Sociétés de bourse',                                          class: 5 },
  { code: '517',    name: 'Autres organismes financiers',                                class: 5 },
  { code: '519',    name: 'Concours bancaires courants',                                 class: 5 },
  { code: '5191',   name: 'Crédits de trésorerie',                                       class: 5 },
  { code: '5193',   name: 'Mobilisations de créances commerciales',                      class: 5 },
  { code: '5198',   name: 'Intérêts courus — découverts',                                class: 5 },
  { code: '521',    name: 'Effets à payer à vue',                                        class: 5 },
  { code: '522',    name: 'Effets à payer dans un délai déterminé',                      class: 5 },
  { code: '530',    name: 'Caisse',                                                      class: 5 },
  { code: '5301',   name: 'Caisse siège social',                                         class: 5 },
  { code: '5311',   name: 'Caisses des établissements',                                  class: 5 },
  { code: '531',    name: 'Caisse (espèces)',                                             class: 5 },
  { code: '540',    name: 'Caisse en devises',                                           class: 5 },
  { code: '580',    name: 'Virements internes',                                          class: 5 },
  { code: '590',    name: 'Dépréciations des valeurs mobilières de placement',           class: 5 },

  // ─────────────────────────────────────────────────────────────────────
  // CLASSE 6 — Comptes de charges
  // ─────────────────────────────────────────────────────────────────────
  { code: '601',    name: 'Achats stockés de matières premières',                        class: 6 },
  { code: '602',    name: 'Achats stockés — autres approvisionnements',                  class: 6 },
  { code: '603',    name: 'Variations des stocks',                                       class: 6 },
  { code: '6031',   name: 'Variations des stocks de matières premières',                 class: 6 },
  { code: '6032',   name: "Variations des stocks d'autres approvisionnements",           class: 6 },
  { code: '604',    name: "Achats d'études et de prestations de services",               class: 6 },
  { code: '605',    name: "Achats de matériel, équipements et travaux",                  class: 6 },
  { code: '606',    name: 'Achats non stockés de matières et fournitures',               class: 6 },
  { code: '6061',   name: 'Fournitures non stockables (eau, énergie)',                   class: 6 },
  { code: '6063',   name: "Fournitures d'entretien et de petit équipement",              class: 6 },
  { code: '6064',   name: 'Fournitures administratives',                                 class: 6 },
  { code: '6068',   name: 'Autres matières et fournitures',                              class: 6 },
  { code: '607',    name: 'Achats de marchandises',                                      class: 6 },
  { code: '608',    name: 'Frais accessoires sur achats',                                class: 6 },
  { code: '609',    name: 'Rabais, remises et ristournes obtenus sur achats',            class: 6 },
  { code: '611',    name: 'Sous-traitance générale',                                     class: 6 },
  { code: '612',    name: 'Redevances de crédit-bail',                                   class: 6 },
  { code: '6122',   name: 'Crédit-bail mobilier',                                        class: 6 },
  { code: '6125',   name: 'Crédit-bail immobilier',                                      class: 6 },
  { code: '613',    name: 'Locations',                                                   class: 6 },
  { code: '6132',   name: 'Locations immobilières',                                      class: 6 },
  { code: '6135',   name: 'Locations mobilières',                                        class: 6 },
  { code: '614',    name: 'Charges locatives et de copropriété',                         class: 6 },
  { code: '615',    name: 'Entretiens et réparations',                                   class: 6 },
  { code: '6152',   name: 'Entretiens et réparations sur biens mobiliers',               class: 6 },
  { code: '6155',   name: 'Entretiens et réparations sur biens immobiliers',             class: 6 },
  { code: '616',    name: "Primes d'assurance",                                          class: 6 },
  { code: '6161',   name: "Assurances multirisques",                                     class: 6 },
  { code: '6162',   name: 'Assurances obligatoires dommages construction',               class: 6 },
  { code: '6163',   name: "Assurance transport",                                         class: 6 },
  { code: '6168',   name: "Autres primes d'assurance",                                   class: 6 },
  { code: '617',    name: 'Études et recherches',                                        class: 6 },
  { code: '618',    name: 'Divers',                                                      class: 6 },
  { code: '619',    name: 'Rabais, remises et ristournes obtenus sur services',          class: 6 },
  { code: '621',    name: "Personnel extérieur à l'entreprise",                          class: 6 },
  { code: '622',    name: "Rémunérations d'intermédiaires et honoraires",                class: 6 },
  { code: '6221',   name: 'Commissions et courtages',                                    class: 6 },
  { code: '6222',   name: "Rémunérations d'intermédiaires",                              class: 6 },
  { code: '6224',   name: 'Honoraires',                                                  class: 6 },
  { code: '6226',   name: 'Honoraires de commissaires aux comptes',                      class: 6 },
  { code: '6227',   name: 'Frais d\'actes et de contentieux',                            class: 6 },
  { code: '6228',   name: 'Divers',                                                      class: 6 },
  { code: '623',    name: 'Publicité, publications, relations publiques',                class: 6 },
  { code: '6231',   name: 'Annonces et insertions',                                      class: 6 },
  { code: '6232',   name: 'Échantillons',                                                class: 6 },
  { code: '6233',   name: 'Foires et expositions',                                       class: 6 },
  { code: '6234',   name: 'Cadeaux à la clientèle',                                      class: 6 },
  { code: '6235',   name: 'Prospectus, catalogues, imprimés',                            class: 6 },
  { code: '6236',   name: 'Parrainage et mécénat',                                       class: 6 },
  { code: '6238',   name: 'Divers (publicité)',                                          class: 6 },
  { code: '624',    name: 'Transports de biens et transports collectifs du personnel',   class: 6 },
  { code: '6241',   name: 'Transports sur achats',                                       class: 6 },
  { code: '6242',   name: 'Transports sur ventes',                                       class: 6 },
  { code: '6243',   name: 'Transports entre établissements',                             class: 6 },
  { code: '6244',   name: 'Transports administratifs',                                   class: 6 },
  { code: '6247',   name: 'Transports collectifs du personnel',                          class: 6 },
  { code: '6248',   name: 'Autres transports',                                           class: 6 },
  { code: '625',    name: 'Déplacements, missions et réceptions',                        class: 6 },
  { code: '6251',   name: 'Voyages et déplacements',                                     class: 6 },
  { code: '6255',   name: 'Frais de déménagement',                                       class: 6 },
  { code: '6256',   name: 'Missions',                                                    class: 6 },
  { code: '6257',   name: 'Réceptions',                                                  class: 6 },
  { code: '626',    name: 'Frais postaux et de télécommunications',                      class: 6 },
  { code: '6261',   name: 'Frais d\'affranchissement',                                   class: 6 },
  { code: '6262',   name: 'Frais de télécommunications',                                 class: 6 },
  { code: '627',    name: 'Services bancaires et assimilés',                             class: 6 },
  { code: '6271',   name: 'Frais sur titres (achats, ventes, garde)',                    class: 6 },
  { code: '6272',   name: 'Commissions et frais bancaires',                              class: 6 },
  { code: '628',    name: 'Divers',                                                      class: 6 },
  { code: '6281',   name: 'Concours divers (centres de gestion agréés)',                 class: 6 },
  { code: '6288',   name: 'Autres services extérieurs',                                  class: 6 },
  { code: '629',    name: 'Rabais, remises obtenus sur services extérieurs',             class: 6 },
  { code: '631',    name: 'Impôts, taxes et versements sur rémunérations',              class: 6 },
  { code: '6311',   name: 'Taxe sur les salaires',                                       class: 6 },
  { code: '6312',   name: "Taxe d'apprentissage",                                        class: 6 },
  { code: '6313',   name: 'Participation des employeurs à la formation professionnelle', class: 6 },
  { code: '6314',   name: 'Cotisation patronale — effort de construction',               class: 6 },
  { code: '633',    name: 'Impôts, taxes et versements assimilés',                       class: 6 },
  { code: '6331',   name: 'TVA non récupérable',                                         class: 6 },
  { code: '6333',   name: 'Impôts et taxes divers',                                      class: 6 },
  { code: '635',    name: 'Autres impôts, taxes et versements assimilés',                class: 6 },
  { code: '6351',   name: 'Impôts directs (sauf IS)',                                    class: 6 },
  { code: '6352',   name: 'Taxes sur le CA non récupérables',                            class: 6 },
  { code: '6353',   name: "Taxes à l'importation",                                       class: 6 },
  { code: '6354',   name: 'Taxes sur produits',                                          class: 6 },
  { code: '6358',   name: 'Autres droits',                                               class: 6 },
  { code: '637',    name: 'Autres impôts, taxes et versements assimilés',                class: 6 },
  { code: '641',    name: 'Rémunérations du personnel',                                  class: 6 },
  { code: '6411',   name: 'Salaires et appointements',                                   class: 6 },
  { code: '6412',   name: 'Congés payés',                                                class: 6 },
  { code: '6413',   name: 'Primes et gratifications',                                    class: 6 },
  { code: '6414',   name: 'Indemnités et avantages divers',                              class: 6 },
  { code: '6415',   name: 'Supplément familial',                                         class: 6 },
  { code: '644',    name: "Rémunérations du travail de l'exploitant",                    class: 6 },
  { code: '645',    name: 'Charges de sécurité sociale et de prévoyance',               class: 6 },
  { code: '6451',   name: "Cotisations à l'URSSAF",                                      class: 6 },
  { code: '6452',   name: 'Cotisations aux mutuelles',                                   class: 6 },
  { code: '6453',   name: 'Cotisations aux caisses de retraite',                         class: 6 },
  { code: '6454',   name: "Cotisations aux ASSEDIC",                                     class: 6 },
  { code: '6455',   name: 'Cotisations aux caisses de prévoyance',                       class: 6 },
  { code: '647',    name: 'Autres charges sociales',                                     class: 6 },
  { code: '6472',   name: 'Versements aux comités d\'entreprise',                        class: 6 },
  { code: '6474',   name: 'Versements au titre de la participation',                     class: 6 },
  { code: '6478',   name: 'Autres charges sociales diverses',                            class: 6 },
  { code: '648',    name: 'Autres charges de personnel',                                 class: 6 },
  { code: '651',    name: 'Redevances pour concessions, brevets, licences',              class: 6 },
  { code: '653',    name: 'Jetons de présence',                                          class: 6 },
  { code: '654',    name: 'Pertes sur créances irrécouvrables',                          class: 6 },
  { code: '655',    name: 'Quotes-parts de résultat — opérations en commun',             class: 6 },
  { code: '658',    name: 'Charges diverses de gestion courante',                        class: 6 },
  { code: '661',    name: "Charges d'intérêts",                                          class: 6 },
  { code: '6611',   name: 'Intérêts des emprunts et dettes',                             class: 6 },
  { code: '6612',   name: 'Intérêts des obligations convertibles',                       class: 6 },
  { code: '6615',   name: 'Intérêts des comptes courants créditeurs',                    class: 6 },
  { code: '6616',   name: 'Intérêts bancaires et sur opérations de financement',         class: 6 },
  { code: '662',    name: 'Pertes sur créances liées à des participations',              class: 6 },
  { code: '664',    name: 'Pertes sur placements',                                       class: 6 },
  { code: '665',    name: 'Escomptes accordés',                                          class: 6 },
  { code: '666',    name: 'Pertes de change',                                            class: 6 },
  { code: '667',    name: 'Charges nettes sur cessions de valeurs mobilières',           class: 6 },
  { code: '668',    name: 'Autres charges financières',                                  class: 6 },
  { code: '671',    name: 'Charges exceptionnelles sur opérations de gestion',           class: 6 },
  { code: '6711',   name: 'Pénalités sur marchés',                                       class: 6 },
  { code: '6712',   name: 'Pénalités, amendes fiscales et pénales',                      class: 6 },
  { code: '6713',   name: 'Dons, libéralités',                                           class: 6 },
  { code: '6714',   name: 'Créances irrécouvrables dans l\'exercice',                    class: 6 },
  { code: '6717',   name: "Rappels d'impôts",                                            class: 6 },
  { code: '6718',   name: 'Autres charges exceptionnelles sur opérations de gestion',    class: 6 },
  { code: '675',    name: "Valeurs comptables des éléments d'actif cédés",               class: 6 },
  { code: '676',    name: 'Différences sur réalisations de placements',                  class: 6 },
  { code: '678',    name: 'Autres charges exceptionnelles',                              class: 6 },
  { code: '681',    name: 'Dotations aux amortissements — charges d\'exploitation',      class: 6 },
  { code: '6811',   name: 'Dotations aux amortissements sur immobilisations',            class: 6 },
  { code: '6815',   name: 'Dotations aux dépréciations des immobilisations',             class: 6 },
  { code: '6816',   name: 'Dotations aux dépréciations des actifs circulants',           class: 6 },
  { code: '6817',   name: 'Dotations aux provisions',                                    class: 6 },
  { code: '686',    name: 'Dotations aux amortissements — charges financières',          class: 6 },
  { code: '687',    name: 'Dotations aux amortissements — charges exceptionnelles',      class: 6 },
  { code: '691',    name: 'Participation des salariés aux résultats',                    class: 6 },
  { code: '695',    name: 'Impôts sur les bénéfices',                                   class: 6 },
  { code: '696',    name: "Suppléments d'impôt sur les sociétés liés",                  class: 6 },
  { code: '697',    name: 'Imposition forfaitaire annuelle',                             class: 6 },
  { code: '699',    name: 'Produits — reports en arrière des déficits',                  class: 6 },

  // ─────────────────────────────────────────────────────────────────────
  // CLASSE 7 — Comptes de produits
  // ─────────────────────────────────────────────────────────────────────
  { code: '701',    name: 'Ventes de produits finis',                                    class: 7 },
  { code: '702',    name: 'Ventes de produits intermédiaires',                           class: 7 },
  { code: '703',    name: 'Ventes de produits résiduels',                                class: 7 },
  { code: '704',    name: 'Travaux',                                                     class: 7 },
  { code: '705',    name: 'Études',                                                      class: 7 },
  { code: '706',    name: 'Prestations de services',                                     class: 7 },
  { code: '707',    name: 'Ventes de marchandises',                                      class: 7 },
  { code: '708',    name: "Produits des activités annexes",                              class: 7 },
  { code: '7081',   name: "Produits des services exploités dans l'intérêt du personnel", class: 7 },
  { code: '7082',   name: 'Commissions et courtages',                                    class: 7 },
  { code: '7083',   name: 'Locations diverses',                                          class: 7 },
  { code: '7084',   name: 'Mise à disposition de personnel',                             class: 7 },
  { code: '7085',   name: 'Ports et frais accessoires facturés',                         class: 7 },
  { code: '7086',   name: 'Bonis sur reprises d\'emballages consignés',                  class: 7 },
  { code: '7088',   name: "Autres produits d'activités annexes",                         class: 7 },
  { code: '709',    name: 'Rabais, remises et ristournes accordés',                      class: 7 },
  { code: '711',    name: 'Variations des stocks de produits en cours',                  class: 7 },
  { code: '7111',   name: "Variations des en-cours de production de biens",              class: 7 },
  { code: '7112',   name: "Variations des en-cours de production de services",           class: 7 },
  { code: '7113',   name: "Variations des en-cours de travaux",                          class: 7 },
  { code: '7117',   name: 'Variations des stocks de produits finis',                     class: 7 },
  { code: '713',    name: 'Variations des stocks de travaux en cours',                   class: 7 },
  { code: '721',    name: 'Production immobilisée — immobilisations incorporelles',       class: 7 },
  { code: '722',    name: 'Production immobilisée — immobilisations corporelles',         class: 7 },
  { code: '731',    name: "Variations des en-cours",                                     class: 7 },
  { code: '740',    name: "Subventions d'exploitation",                                  class: 7 },
  { code: '741',    name: "Subventions d'exploitation",                                  class: 7 },
  { code: '742',    name: "Subventions d'équilibre",                                     class: 7 },
  { code: '743',    name: 'Remboursement de charges de personnel par l\'État',           class: 7 },
  { code: '744',    name: "Remboursement d'autres charges d'exploitation par l'État",    class: 7 },
  { code: '745',    name: 'Subventions accordées par les collectivités locales',         class: 7 },
  { code: '748',    name: "Autres subventions d'exploitation",                           class: 7 },
  { code: '751',    name: 'Redevances pour concessions, brevets, licences',              class: 7 },
  { code: '752',    name: 'Revenus des immeubles non affectés aux activités',            class: 7 },
  { code: '753',    name: "Jetons de présence et rémunérations d'administrateurs",       class: 7 },
  { code: '754',    name: 'Ristournes perçues des coopératives',                         class: 7 },
  { code: '755',    name: 'Quotes-parts de résultat — opérations en commun',             class: 7 },
  { code: '758',    name: 'Produits divers de gestion courante',                         class: 7 },
  { code: '761',    name: 'Produits de participations',                                  class: 7 },
  { code: '762',    name: 'Produits des autres immobilisations financières',             class: 7 },
  { code: '763',    name: 'Revenus des autres créances',                                 class: 7 },
  { code: '764',    name: 'Revenus des valeurs mobilières de placement',                 class: 7 },
  { code: '765',    name: 'Escomptes obtenus',                                           class: 7 },
  { code: '766',    name: 'Gains de change',                                             class: 7 },
  { code: '767',    name: 'Produits nets sur cessions de valeurs mobilières',            class: 7 },
  { code: '768',    name: 'Autres produits financiers',                                  class: 7 },
  { code: '771',    name: 'Produits exceptionnels sur opérations de gestion',            class: 7 },
  { code: '7711',   name: "Subventions d'équilibre",                                     class: 7 },
  { code: '7713',   name: 'Libéralités reçues',                                          class: 7 },
  { code: '7714',   name: 'Rentrées sur créances amorties',                              class: 7 },
  { code: '7717',   name: 'Rappels de subventions',                                      class: 7 },
  { code: '775',    name: "Produits des cessions d'éléments d'actif",                    class: 7 },
  { code: '776',    name: 'Différences sur réalisations de placements',                  class: 7 },
  { code: '777',    name: 'Quote-part des subventions d\'investissement virée au résultat', class: 7 },
  { code: '778',    name: 'Autres produits exceptionnels',                               class: 7 },
  { code: '781',    name: 'Reprises sur amortissements, dépréciations et provisions',    class: 7 },
  { code: '7811',   name: 'Reprises sur amortissements des immobilisations',             class: 7 },
  { code: '7815',   name: 'Reprises sur dépréciations des immobilisations',              class: 7 },
  { code: '7816',   name: 'Reprises sur dépréciations des actifs circulants',            class: 7 },
  { code: '7817',   name: 'Reprises sur provisions',                                     class: 7 },
  { code: '786',    name: 'Reprises sur dépréciations et provisions financières',        class: 7 },
  { code: '787',    name: 'Reprises sur provisions exceptionnelles',                     class: 7 },
  { code: '791',    name: "Transferts de charges d'exploitation",                        class: 7 },
  { code: '796',    name: 'Transferts de charges financières',                           class: 7 },
  { code: '797',    name: 'Transferts de charges exceptionnelles',                       class: 7 },
];

@Injectable()
export class InitPcgUseCase {
  constructor(
    @Inject(ACCOUNTS_REPOSITORY)
    private readonly accountRepository: AccountRepository,
  ) {}

  async execute(userId: number): Promise<{ created: number; skipped: number }> {
    const existing = await this.accountRepository.findAccounts(userId);
    const existingCodes = new Set(existing.map(a => a.code));

    let created = 0;
    let skipped = 0;

    for (const entry of PCG) {
      if (existingCodes.has(entry.code)) {
        skipped++;
        continue;
      }
      await this.accountRepository.create(
        new Account(entry.code, entry.name, entry.class, undefined, true),
        userId,
      );
      created++;
    }

    return { created, skipped };
  }
}
